=== dumitka/xml-i-web-servisi/xml_dokumenti/Izvestaj_o_imunizaciji.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified"
    targetNamespace="http://www.baklavice.com/izvestaj" vc:minVersion="1.1"
    attributeFormDefault="unqualified" xmlns:izvestaj="http://www.baklavice.com/izvestaj"
    xmlns:tipovi="http://www.baklavice.com/tipovi"
    xmlns:vc="http://www.w3.org/2007/XMLSchema-versioning">
    <xs:import namespace="http://www.baklavice.com/tipovi" schemaLocation="Tipovi.xsd"/>
    <xs:element name="Izvestaj">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="Period">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="Datum_od" type="xs:date"/>
                            <xs:element name="Datum_do" type="xs:date"/>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
                <xs:element name="Broj_interesovanja" type="xs:positiveInteger"/>
                <xs:element name="Zahtevi_za_sertifikat" type="xs:positiveInteger"/>
                <xs:element name="Izdati_sertifikati" type="xs:positiveInteger"/>
                <xs:element name="Doze_vakcine">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="Ukupno_datih_doza" type="xs:positiveInteger"/>
                            <xs:element maxOccurs="unbounded" name="Doza">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="Broj_datih_doza" type="xs:positiveInteger"
                                        />
                                    </xs:sequence>
                                    <xs:attribute name="Redni_broj" type="xs:positiveInteger"
                                        use="required"/>
                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
                <xs:element name="Raspodela_proizvodjaca">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="Proizvodjac" maxOccurs="unbounded">
                                <xs:complexType>
                                    <xs:simpleContent>
                                        <xs:extension base="tipovi:TVakcina">
                                            <xs:attribute name="Broj_doza" type="xs:positiveInteger"
                                                use="required"/>
                                        </xs:extension>
                                    </xs:simpleContent>
                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
                <xs:element name="Datum_izdavanja" type="xs:date"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== dumitka/xml-i-web-servisi/officials/data/Izvestaj_o_imunizaciji.xml
<?xml version="1.0" encoding="UTF-8"?>
<Izvestaj xmlns="http://www.baklavice.com/izvestaj"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="http://www.baklavice.com/izvestaj Izvestaj_o_imunizaciji.xsd"
    xmlns:tipovi="http://www.baklavice.com/tipovi">
    <Sifra_izvestaja>123</Sifra_izvestaja>
    <Period>
        <Datum_od>2021-10-01</Datum_od>
        <Datum_do>2021-11-01</Datum_do>
    </Period>
    <Broj_interesovanja>2758</Broj_interesovanja>
    <Zahtevi_za_sertifikat>456</Zahtevi_za_sertifikat>
    <Izdati_sertifikati>412</Izdati_sertifikati>
    <Doze_vakcine>
        <Ukupno_datih_doza>3225</Ukupno_datih_doza>
        <Doza Redni_broj="1">
            <Broj_datih_doza>1789</Broj_datih_doza>
        </Doza>
        <Doza Redni_broj="2">
            <Broj_datih_doza>1276</Broj_datih_doza>
        </Doza>
        <Doza Redni_broj="3">
            <Broj_datih_doza>160</Broj_datih_doza>
        </Doza>
    </Doze_vakcine>
    <Raspodela_proizvodjaca>
        <Proizvodjac>
            <Naziv_proizvodjaca>Pfizer-BioNTech</Naziv_proizvodjaca>
            <Broj_doza>1625</Broj_doza>
        </Proizvodjac>
        <Proizvodjac>
            <Naziv_proizvodjaca>Sinopharm</Naziv_proizvodjaca>
            <Broj_doza>1100</Broj_doza>
        </Proizvodjac>
        <Proizvodjac>
            <Naziv_proizvodjaca>Sputnik V</Naziv_proizvodjaca>
            <Broj_doza>356</Broj_doza>
        </Proizvodjac>
        <Proizvodjac>
            <Naziv_proizvodjaca>AstraZeneca</Naziv_proizvodjaca>
            <Broj_doza>144</Broj_doza>
        </Proizvodjac>
    </Raspodela_proizvodjaca>
    <Datum_izdavanja>2021-12-01</Datum_izdavanja>
</Izvestaj>

=== dumitka/xml-i-web-servisi/STARI_xml_dokumenti/Izvestaj_o_imunizaciji.xml
<?xml version="1.0" encoding="UTF-8"?>
<Izvestaj xmlns="http://www.baklavice.com/izvestaj"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="http://www.baklavice.com/izvestaj Izvestaj_o_imunizaciji.xsd"
    xmlns:tipovi="http://www.baklavice.com/tipovi">
    <Sifra_izvestaja>123</Sifra_izvestaja>
    <Period>
        <Datum_od>2021-10-01</Datum_od>
        <Datum_do>2021-11-01</Datum_do>
    </Period>
    <Broj_interesovanja>2758</Broj_interesovanja>
    <Zahtevi_za_sertifikat>456</Zahtevi_za_sertifikat>
    <Izdati_sertifikati>412</Izdati_sertifikati>
    <Doze_vakcine>
        <Ukupno_datih_doza>3225</Ukupno_datih_doza>
        <Doza Redni_broj="1">
            <Broj_datih_doza>1789</Broj_datih_doza>
        </Doza>
        <Doza Redni_broj="2">
            <Broj_datih_doza>1276</Broj_datih_doza>
        </Doza>
        <Doza Redni_broj="3">
            <Broj_datih_doza>160</Broj_datih_doza>
        </Doza>
    </Doze_vakcine>
    <Raspodela_proizvodjaca>
        <Proizvodjac Broj_doza="1625">Pfizer-BioNTech</Proizvodjac>
        <Proizvodjac Broj_doza="1100">Sinopharm</Proizvodjac>
        <Proizvodjac Broj_doza="356">Sputnik V</Proizvodjac>
        <Proizvodjac Broj_doza="144">AstraZeneca</Proizvodjac>
    </Raspodela_proizvodjaca>
    <Datum_izdavanja>2021-12-01</Datum_izdavanja>
</Izvestaj>

=== dumitka/xml-i-web-servisi/officials/data/xml/Izvestaj_o_imunizaciji.xml
<?xml version="1.0" encoding="UTF-8"?>
<Izvestaj xmlns="http://www.baklavice.com/izvestaj"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="http://www.baklavice.com/izvestaj Izvestaj_o_imunizaciji.xsd"
    xmlns:tipovi="http://www.baklavice.com/tipovi"
    xmlns:pred="http://www.baklavice.com/rdf/predikati/"
    vocab="http://www.baklavice.com/rdf/predikati/"
    about="http://www.baklavice.com/rdf/izvestaj/123">
    <Sifra_izvestaja>123</Sifra_izvestaja>
    <Period>
        <Datum_od>2021-10-01</Datum_od>
        <Datum_do>2021-11-01</Datum_do>
    </Period>
    <Broj_interesovanja property="pred:broj_interesovanja" datatype="xsi:positiveInteger">2758</Broj_interesovanja>
    <Zahtevi_za_sertifikat property="pred:zahtevi_za_sertifikat" datatype="xsi:positiveInteger">456</Zahtevi_za_sertifikat>
    <Izdati_sertifikati property="pred:izdati_sertifikati" datatype="xsi:positiveInteger">412</Izdati_sertifikati>
    <Doze_vakcine>
        <Ukupno_datih_doza>3225</Ukupno_datih_doza>
        <Doza Redni_broj="1">
            <Broj_datih_doza>1789</Broj_datih_doza>
        </Doza>
        <Doza Redni_broj="2">
            <Broj_datih_doza>1276</Broj_datih_doza>
        </Doza>
        <Doza Redni_broj="3">
            <Broj_datih_doza>160</Broj_datih_doza>
        </Doza>
    </Doze_vakcine>
    <Raspodela_proizvodjaca>
        <Proizvodjac>
            <Naziv_proizvodjaca>Pfizer-BioNTech</Naziv_proizvodjaca>
            <Broj_doza>1625</Broj_doza>
        </Proizvodjac>
        <Proizvodjac>
            <Naziv_proizvodjaca>Sinopharm</Naziv_proizvodjaca>
            <Broj_doza>1100</Broj_doza>
        </Proizvodjac>
        <Proizvodjac>
            <Naziv_proizvodjaca>Sputnik V</Naziv_proizvodjaca>
            <Broj_doza>356</Broj_doza>
        </Proizvodjac>
        <Proizvodjac>
            <Naziv_proizvodjaca>AstraZeneca</Naziv_proizvodjaca>
            <Broj_doza>144</Broj_doza>
        </Proizvodjac>
    </Raspodela_proizvodjaca>
    <Datum_izdavanja property="pred:datum_izdavanja" datatype="xsi:date">2021-12-01</Datum_izdavanja>
</Izvestaj>
